//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5477
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

/// This class was created from file C:\Users\Diprove\Desktop\Reimplementazione\SoilT\UNIMI.SoilT_perSoilBorne\UNIMI.SoilT\DataStructure\SoilTemperatureStatesExternal.xml
/// DCC - Domain Class Coder, http://agsys.cra-cin.it/tools , see Applications, DCC
namespace UNIMI.SoilT.Interfaces
{
    using System;
    using CRA.ModelLayer;
    using CRA.ModelLayer.Core;
    
    
    /// <summary>StatesExternalVarInfoClasses contain the attributes for each variable in the domain class RainData. Attributes are valorized via the static constructor. The data-type VarInfo causes  a dependency to the assembly CRA.ModelLayer.dll</summary>
    public class StatesExternalVarInfo : IVarInfoClass
    {
        
        #region Private fields
        static VarInfo _GreenLeafAreaIndex = new VarInfo();
        
        static VarInfo _AboveGroundBiomass = new VarInfo();
        #endregion
        
        /// <summary>Constructor</summary>
        static StatesExternalVarInfo()
        {
            StatesExternalVarInfo.DescribeVariables();
        }
        
        #region IVarInfoClass members
        /// <summary>Domain Class description</summary>
        public virtual  string Description
        {
            get
            {
                return "State external variables of SoilT component ";
            }
        }
        
        /// <summary>Reference to the ontology</summary>
        public  string URL
        {
            get
            {
                return "http://";
            }
        }
        
        /// <summary>Value domain class of reference</summary>
        public  string DomainClassOfReference
        {
            get
            {
                return "StatesExternal";
            }
        }
        #endregion
        
        #region Public properties
        /// <summary>Green leaf area index</summary>
        public static  VarInfo GreenLeafAreaIndex
        {
            get
            {
                return  _GreenLeafAreaIndex;
            }
        }
        
        /// <summary>Above ground biomass</summary>
        public static  VarInfo AboveGroundBiomass
        {
            get
            {
                return  _AboveGroundBiomass;
            }
        }
        #endregion
        
        #region VarInfo values
        /// <summary>Set VarInfo values</summary>
        static void DescribeVariables()
        {
            //   
            _GreenLeafAreaIndex.Name = "GreenLeafAreaIndex";
            _GreenLeafAreaIndex.Description = "Green leaf area index";
            _GreenLeafAreaIndex.MaxValue = 20;
            _GreenLeafAreaIndex.MinValue = 0;
            _GreenLeafAreaIndex.DefaultValue = 4;
            _GreenLeafAreaIndex.Units = "m2 m-2";
            _GreenLeafAreaIndex.URL = "http://";
            _GreenLeafAreaIndex.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
            //   
            _AboveGroundBiomass.Name = "AboveGroundBiomass";
            _AboveGroundBiomass.Description = "Above ground biomass";
            _AboveGroundBiomass.MaxValue = 60;
            _AboveGroundBiomass.MinValue = 0;
            _AboveGroundBiomass.DefaultValue = 3;
            _AboveGroundBiomass.Units = "Kg ha-1";
            _AboveGroundBiomass.URL = "http://";
            _AboveGroundBiomass.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
        }
        #endregion
    }
}
