//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5477
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

/// This class was created from file C:\Users\Diprove\Desktop\Reimplementazione\SoilT\UNIMI.SoilT_perSoilBorne\UNIMI.SoilT\DataStructure\SoilTemperatureRates.xml
/// DCC - Domain Class Coder, http://agsys.cra-cin.it/tools , see Applications, DCC
namespace UNIMI.SoilT.Interfaces
{
    using System;
    using CRA.ModelLayer;
    using CRA.ModelLayer.Core;
    
    
    /// <summary>RatesVarInfoClasses contain the attributes for each variable in the domain class RainData. Attributes are valorized via the static constructor. The data-type VarInfo causes  a dependency to the assembly CRA.ModelLayer.dll</summary>
    public class RatesVarInfo : IVarInfoClass
    {

        #region Private fields
        //static VarInfo _Layers = new VarInfo();
        static VarInfo _SoilTemperatureByLayersChange = new VarInfo();

        static VarInfo _BulkDensityChange = new VarInfo();

        static VarInfo _t = new VarInfo();
        #endregion
        
        /// <summary>Constructor</summary>
        static RatesVarInfo()
        {
            RatesVarInfo.DescribeVariables();
        }
        
        #region IVarInfoClass members
        /// <summary>Domain Class description</summary>
        public virtual  string Description
        {
            get
            {
                return "Rate variables of SoilT component ";
            }
        }
        
        /// <summary>Reference to the ontology</summary>
        public  string URL
        {
            get
            {
                return "http://";
            }
        }
        
        /// <summary>Value domain class of reference</summary>
        public  string DomainClassOfReference
        {
            get
            {
                return "Rates";
            }
        }
        #endregion

        #region Public properties

        public static VarInfo SoilTemperatureByLayersChange
        {
            get
            {
                return _SoilTemperatureByLayersChange;
            }
        }

        /// <summary>Change of bulk density</summary>
        public static VarInfo BulkDensityChange
        {
            get
            {
                return _BulkDensityChange;
            }
        }

        /// <summary></summary>
        public static  VarInfo t
        {
            get
            {
                return  _t;
            }
        }
        #endregion
        
        #region VarInfo values
        /// <summary>Set VarInfo values</summary>
        static void DescribeVariables()
        {
            ////   
            //_Layers.Name = "Layers";
            //_Layers.Description = "Rates of soil layer";
            //_Layers.MaxValue = 0;
            //_Layers.MinValue = 0;
            //_Layers.DefaultValue = 0;
            //_Layers.Units = "unitless";
            //_Layers.URL = "http://";
            //_Layers.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
            //
            ////   
            _SoilTemperatureByLayersChange.Name = "SoilTemperatureByLayersChange";
            _SoilTemperatureByLayersChange.Description = "Change of soil temperature";
            _SoilTemperatureByLayersChange.MaxValue = 60;
            _SoilTemperatureByLayersChange.MinValue = -60;
            _SoilTemperatureByLayersChange.DefaultValue = 0;
            _SoilTemperatureByLayersChange.Units = "°C";
            _SoilTemperatureByLayersChange.URL = "http://";
            _SoilTemperatureByLayersChange.ValueType = VarInfoValueTypes.GetInstanceForName("ArrayDouble");
            //   
            _BulkDensityChange.Name = "BulkDensityChange";
            _BulkDensityChange.Description = "Change of bulk density";
            _BulkDensityChange.MaxValue = 1.8;
            _BulkDensityChange.MinValue = -1.8;
            _BulkDensityChange.DefaultValue = 0;
            _BulkDensityChange.Units = "t m-3";
            _BulkDensityChange.URL = "http://";
            _BulkDensityChange.ValueType = VarInfoValueTypes.GetInstanceForName("ArrayDouble");
            //cyml _t.Name = "t";
            //cyml _t.Description = "";
            //cyml _t.MaxValue = 0;
            //cyml _t.MinValue = 0;
            //cyml _t.DefaultValue = 0;
            //cyml _t.Units = "int";
            //cyml _t.URL = "";
            //cyml _t.ValueType = VarInfoValueTypes.GetInstanceForName("DoubleMatrix");
        }
        #endregion
    }
}
