//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5477
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

/// This class was created from file C:\Users\Diprove\Desktop\Reimplementazione\SoilT\UNIMI.SoilT_perSoilBorne\UNIMI.SoilT\DataStructure\SoilTemperatureRates.xml
/// DCC - Domain Class Coder, http://agsys.cra-cin.it/tools , see Applications, DCC
// 
namespace UNIMI.SoilT.Interfaces
{
    using System;
    using System.Collections.Generic;
    using CRA.ModelLayer;
    using System.Reflection;
    using CRA.ModelLayer.ParametersManagement;
    using CRA.ModelLayer.Core;
    
    
    /// <summary>Rates Domain class contains the accessors to values</summary>
    public class Rates : ICloneable, IDomainClass
    {

        #region Private fields
        //private List<LayerRates> _Layers =new List<LayerRates>();
        // new type - begin
        private double[] _SoilTemperatureByLayersChange;

        private double[] _BulkDensityChange;
        // new type - end

        private double[,] _t;
        #endregion
        
        #region Private field for properties
        private ParametersIO _parametersIO;
        #endregion
        
        #region Constructor
        /// <summary>No parameters constructor</summary>
        public Rates()
        {
            _parametersIO = new ParametersIO(this);
        }
        #endregion

        #region Public properties
        /// <summary>Rates of soil layer</summary>
        //public List<LayerRates> Layers
        //{
        //    get
        //    {
        //        return this._Layers;
        //    }
        //    set
        //    {
        //        this._Layers = value;
        //    }
        //}

        public double[] SoilTemperatureByLayersChange
        {
            get
            {
                return this._SoilTemperatureByLayersChange;
            }
            set
            {
                this._SoilTemperatureByLayersChange = value;
            }
        }

        /// <summary>Change of bulk density</summary>
        public double[] BulkDensityChange
        {
            get
            {
                return this._BulkDensityChange;
            }
            set
            {
                this._BulkDensityChange = value;
            }
        }

        /// <summary></summary>
        public double[,] t
        {
            get
            {
                return this._t;
            }
            set
            {
                this._t = value;
            }
        }
        #endregion
        
        #region IDomainClass members
        /// <summary>Domain Class description</summary>
        public virtual  string Description
        {
            get
            {
                return "Rate variables of SoilT component ";
            }
        }
        
        /// <summary>Domain Class URL</summary>
        public virtual  string URL
        {
            get
            {
                return "http://";
            }
        }
        
        /// <summary>Domain Class Properties</summary>
        public virtual IDictionary<string, PropertyInfo> PropertiesDescription
        {
            get
            {
                return _parametersIO.GetCachedProperties(typeof(IDomainClass));
            }
        }
        #endregion

        /// <summary>Clears the values of the properties of the domain class by using the default value for the type of each property (e.g '0' for numbers, 'the empty string' for strings, etc.)</summary>
        public virtual Boolean ClearValues()
        {
            //_Layers = default(List<LayerRates>);
            _SoilTemperatureByLayersChange = default(double[]);
            _BulkDensityChange = default(double[]);
            _t = default(System.Double[,]);
            // Returns true if everything is ok
            return true;
        }
        
        #region Clone
        /// <summary>Implement ICloneable.Clone()</summary>
        public virtual Object Clone()
        {
            // Shallow copy by default
            IDomainClass myclass = (IDomainClass) this.MemberwiseClone();
            _parametersIO.PopulateClonedCopy(myclass);
            return myclass;
        }
        #endregion

        /// <summary>
        /// Initializes the structure.
        /// </summary>
        public void Initialize()
        {
            Initialize(false, 0);
        }

        /// <summary>
        /// Initializes the structure.
        /// </summary>
        /// <param name="resetLayersNumber"><c>true</c> if horizon list has
        /// to be initialized.</param>
        /// <param name="layersNumber">Number of layers to set.</param>
        public void Initialize(bool resetLayersNumber, int layersNumber)
        {
            if (resetLayersNumber)
            {
                if (layersNumber > 0)
                {
                    //Layers = new List<LayerRates>();
                    //LayerRates lr = null;
                    //for (int i = 0; i < layersNumber; i++)
                    //{
                    //    lr = new LayerRates();
                    //    lr.Initialize(resetLayersNumber, layersNumber);
                    //    Layers.Add(lr);
                    //}
                    _SoilTemperatureByLayersChange = new double[layersNumber];
                    _BulkDensityChange = new double[layersNumber];

                }
                else
                {
                    _SoilTemperatureByLayersChange = default(double[]);
                    _BulkDensityChange = default(double[]);
                }
            }
            else
            {
                //if (Layers != null)
                //{
                //    foreach (LayerRates lr in Layers)
                //    {
                //        lr.Initialize();
                //    }
                //}
                if (_SoilTemperatureByLayersChange != null && _SoilTemperatureByLayersChange.Length > 0)
                {
                    var currentLayersNumber = _SoilTemperatureByLayersChange.Length;
                    _SoilTemperatureByLayersChange = new double[currentLayersNumber];
                    _BulkDensityChange = new double[currentLayersNumber];
                }
            }
        }

        /// <summary>
        /// Initializes the structure properties to their default value.
        /// </summary>
        /// <param name="allValues"><c>true</c> if all values have to be set,
        /// <c>false</c> if only <c>NaN</c> or <c>null</c> values have to be set.</param>
        public void SetDefaultValues(bool allValues)
        {
            //if (Layers != null)
            //{
            //    foreach (LayerRates lr in Layers)
            //    {
            //        lr.SetDefaultValues(allValues);
            //    }
            //}
            if (_SoilTemperatureByLayersChange != null && _SoilTemperatureByLayersChange.Length > 0)
            {
                for (int i = 0; i < _SoilTemperatureByLayersChange.Length; i++) { _SoilTemperatureByLayersChange[i] = RatesVarInfo.SoilTemperatureByLayersChange.DefaultValue; }
                for (int i = 0; i < _BulkDensityChange.Length; i++) { _BulkDensityChange[i] = RatesVarInfo.BulkDensityChange.DefaultValue; }
            }
        }
    }
}
