[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"
[project]
name = "BiomaSurfacePartonSoilSWATC"
authors = [{name = "simone.bregaglio@unimi.it"}]
description=""
version="0.1"
dependencies = ["pandas","numpy"]