/*
     -----------------------------------------------------------

     Code generated by CRA.ModelLayer.ACC - API Code Generator
     http://components.biomamodelling.org/components/acc/help/ 

     Loic Manceau
     loic.manceau@inra.fr
     INRA
     6/13/2017 5:14:33 PM

     -----------------------------------------------------------
*/

using System;
using CRA.ModelLayer.Strategy;


namespace INRA.SiriusQualitySoilT.Interfaces
{
    /// <summary>
    /// INRA.SiriusQualitySoilT.Interfaces component model interface   
    /// </summary>
    public interface IStrategySiriusQualitySoilT : IStrategy
    {
        /// <summary>
        /// Calculate method for models
        /// </summary>
        /// <param name=d>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=d1>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=e>Exogenous Domain class contains the accessors to values</param>
        /// <param name=r>RatesExternal Domain class contains the accessors to values</param>
        /// <param name=s>States Domain class contains the accessors to values</param>
        void Estimate
        ( DeepLayerStates d, DeepLayerStates d1, Exogenous e, RatesExternal r, States s);
        
        /// <summary>
        /// Test of pre conditions
        /// </summary>
        /// <param name=d>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=d1>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=e>Exogenous Domain class contains the accessors to values</param>
        /// <param name=r>RatesExternal Domain class contains the accessors to values</param>
        /// <param name=s>States Domain class contains the accessors to values</param>
        /// <param name=callID>Preconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPreConditions( DeepLayerStates d, DeepLayerStates d1, Exogenous e, RatesExternal r, States s, string callID);
        
        /// <summary>
        /// Test of post-conditions
        /// </summary>
        /// <param name=d>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=d1>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=e>Exogenous Domain class contains the accessors to values</param>
        /// <param name=r>RatesExternal Domain class contains the accessors to values</param>
        /// <param name=s>States Domain class contains the accessors to values</param>
        /// <param name=callID>Postconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPostConditions( DeepLayerStates d, DeepLayerStates d1, Exogenous e, RatesExternal r, States s, string callID);
    
        /// <summary>
        /// Set parameters to the default value
        /// </summary>
        void SetParametersDefaultValue();
    }
}
