/*   
     ----------------------------------------------------------------
	 Code generated by CRA.ModelLayer.ACC - API Code Generator
     http://components.biomamodelling.org/components/acc/help/ 

     Loic Manceau
     loic.manceau@inra.fr
     INRA
     6/13/2017 5:14:33 PM
	 ----------------------------------------------------------------
*/

using System;
using System.Collections.Generic;
using System.Text;
using CRA.ModelLayer.Core;

namespace INRA.SiriusQualitySoilT.Interfaces
{
    /// <summary>
    /// INRA.SiriusQualitySoilT.Interfaces component API 
    /// </summary>
    public class SiriusQualitySoilTAPI 
    {
        private string _resultPreConditions;
        private string _resultPostConditions;
        Preconditions p = new Preconditions();

        /// <summary>
        /// Calculate method for the component
        /// </summary>
        /// <param name=d>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=d1>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=e>Exogenous Domain class contains the accessors to values</param>
        /// <param name=r>RatesExternal Domain class contains the accessors to values</param>
        /// <param name=s>States Domain class contains the accessors to values</param>
        public void Estimate
		(IStrategySiriusQualitySoilT st, DeepLayerStates d, DeepLayerStates d1, Exogenous e, RatesExternal r, States s)
        {
            st.Estimate
			( d, d1, e, r, s);
        }
              
        /// <summary>
        /// Calculate method for the component with test of preconditions
        /// </summary>
        /// <param name=d>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=d1>DeepLayerStates Domain class contains the accessors to values</param>
        /// <param name=e>Exogenous Domain class contains the accessors to values</param>
        /// <param name=r>RatesExternal Domain class contains the accessors to values</param>
        /// <param name=s>States Domain class contains the accessors to values</param>
        /// <param name="saveLog">Save log via a writer or show on screen</param>
        /// <param name="callID">Context description for violations</param>
        public void Estimate
            (IStrategySiriusQualitySoilT st, DeepLayerStates d, DeepLayerStates d1, Exogenous e, RatesExternal r, States s, bool saveLog, string callID)        
           {
            _resultPreConditions = String.Empty;
            _resultPostConditions = String.Empty;
            _resultPreConditions = st.TestPreConditions( d, d1, e, r, s, callID);
            st.Estimate
			( d, d1, e, r, s);
            _resultPostConditions = st.TestPostConditions( d, d1, e, r, s, callID);

            if (_resultPreConditions != String.Empty || _resultPostConditions != String.Empty)
            {
                p.TestsOut(_resultPreConditions + _resultPostConditions, saveLog, callID);
            }
        }

        /// <summary>
        /// Show the about form with access to the help and codedoc
        /// </summary>
        public void Info()
        {
            // The following assumes an about form called AboutBox
            //AboutBox a = new AboutBox();
            //a.ShowDialog();
        }
    }
}
 
