//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

/// 
/// This class was created from file C:\Users\mancealo\Documents\Sirius Quality\branches\TestSoil\Code\SiriusQuality-SoilTemperatureDomainClasses\XML\UNIMI.SoilT.Interfaces_DeepLayerStates.xml
/// The tool used was: DCC - Domain Class Coder, http://components.biomamodelling.org/, DCC
/// 
/// Loic Manceau
/// loic.manceau@inra.fr
/// INRA
/// 
/// 
/// 5/8/2017 12:20:39 PM
/// 
namespace INRA.SiriusQualitySoilT.Interfaces
{
    using System;
    using CRA.ModelLayer.Core;
    
    
    /// <summary>DeepLayerStatesVarInfoClasses contain the attributes for each variable in the domain class RainData. Attributes are valorized via the static constructor. The data-type VarInfo causes  a dependency to the assembly CRA.Core.Preconditions.dll</summary>
    public class DeepLayerStatesVarInfo : IVarInfoClass
    {
        
        #region Private fields
        static VarInfo _deepLayerT = new VarInfo();
        #endregion
        
        /// <summary>Constructor</summary>
        static DeepLayerStatesVarInfo()
        {
            DeepLayerStatesVarInfo.DescribeVariables();
        }
        
        #region IVarInfoClass members
        /// <summary>Domain Class description</summary>
        public virtual  string Description
        {
            get
            {
                return "Deep Soil layer states variables of SoilT component ";
            }
        }
        
        /// <summary>Reference to the ontology</summary>
        public  string URL
        {
            get
            {
                return "http://";
            }
        }
        
        /// <summary>Value domain class of reference</summary>
        public  string DomainClassOfReference
        {
            get
            {
                return "DeepLayerStates";
            }
        }
        #endregion
        
        #region Public properties
        /// <summary>Temperature of the last soil layer</summary>
        public static  VarInfo deepLayerT
        {
            get
            {
                return  _deepLayerT;
            }
        }
        #endregion
        
        #region VarInfo values
        /// <summary>Set VarInfo values</summary>
        static void DescribeVariables()
        {
            //   
            _deepLayerT.Name = "deepLayerT";
            _deepLayerT.Description = "Temperature of the last soil layer";
            _deepLayerT.MaxValue = 80D;
            _deepLayerT.MinValue = -30D;
            _deepLayerT.DefaultValue = 20D;
            _deepLayerT.Units = "°C";
            _deepLayerT.URL = "http://";
            _deepLayerT.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
        }
        #endregion
    }
}
