//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

/// 
/// This class was created from file C:\Users\mancealo\Documents\Sirius Quality\branches\TestSoil\Code\SiriusQuality-SoilTemperatureDomainClasses\XML\UNIMI.SoilT.Interfaces_Exogenous.xml
/// The tool used was: DCC - Domain Class Coder, http://components.biomamodelling.org/, DCC
/// 
/// Loic Manceau
/// loic.manceau@inra.fr
/// INRA
/// 
/// 
/// 5/8/2017 12:22:17 PM
/// 
namespace INRA.SiriusQualitySoilT.Interfaces
{
    using System;
    using CRA.ModelLayer.Core;
    
    
    /// <summary>ExogenousVarInfoClasses contain the attributes for each variable in the domain class RainData. Attributes are valorized via the static constructor. The data-type VarInfo causes  a dependency to the assembly CRA.Core.Preconditions.dll</summary>
    public class ExogenousVarInfo : IVarInfoClass
    {
        
        #region Private fields
        static VarInfo _minTAir = new VarInfo();
        
        static VarInfo _maxTAir = new VarInfo();
        
        static VarInfo _meanTAir = new VarInfo();
        
        static VarInfo _dayLength = new VarInfo();

        static VarInfo _meanAnnualAirTemp = new VarInfo();
        #endregion
        
        /// <summary>Constructor</summary>
        static ExogenousVarInfo()
        {
            ExogenousVarInfo.DescribeVariables();
        }
        
        #region IVarInfoClass members
        /// <summary>Domain Class description</summary>
        public virtual  string Description
        {
            get
            {
                return "Exogenous of the SoilT component";
            }
        }
        
        /// <summary>Reference to the ontology</summary>
        public  string URL
        {
            get
            {
                return "http://";
            }
        }
        
        /// <summary>Value domain class of reference</summary>
        public  string DomainClassOfReference
        {
            get
            {
                return "Exogenous";
            }
        }
        #endregion
        
        #region Public properties
        /// <summary>Minimum Air Temperature from Weather files</summary>
        public static  VarInfo minTAir
        {
            get
            {
                return  _minTAir;
            }
        }
        
        /// <summary>Maximum Air Temperature from Weather Files</summary>
        public static  VarInfo maxTAir
        {
            get
            {
                return  _maxTAir;
            }
        }
        
        /// <summary>Mean Air Temperature</summary>
        public static  VarInfo meanTAir
        {
            get
            {
                return  _meanTAir;
            }
        }
        
        /// <summary>Length of the day</summary>
        public static  VarInfo dayLength
        {
            get
            {
                return  _dayLength;
            }
        }

        /// <summary>Annual Mean Air Temperature</summary>
        public static VarInfo meanAnnualAirTemp
        {
            get
            {
                return _meanAnnualAirTemp;
            }
        }
        #endregion

        #region VarInfo values
        /// <summary>Set VarInfo values</summary>
        static void DescribeVariables()
        {
            //   
            _minTAir.Name = "minTAir";
            _minTAir.Description = "Minimum Air Temperature from Weather files";
            _minTAir.MaxValue = 80D;
            _minTAir.MinValue = -30D;
            _minTAir.DefaultValue = 20D;
            _minTAir.Units = "°C";
            _minTAir.URL = "http://";
            _minTAir.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
            //   
            _maxTAir.Name = "maxTAir";
            _maxTAir.Description = "Maximum Air Temperature from Weather Files";
            _maxTAir.MaxValue = 80D;
            _maxTAir.MinValue = -30D;
            _maxTAir.DefaultValue = 25D;
            _maxTAir.Units = "°C";
            _maxTAir.URL = "http://";
            _maxTAir.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
            //   
            _meanTAir.Name = "meanTAir";
            _meanTAir.Description = "Mean Air Temperature";
            _meanTAir.MaxValue = 80D;
            _meanTAir.MinValue = -30D;
            _meanTAir.DefaultValue = 22D;
            _meanTAir.Units = "°C";
            _meanTAir.URL = "http://";
            _meanTAir.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
            //   
            _dayLength.Name = "dayLength";
            _dayLength.Description = "Length of the day";
            _dayLength.MaxValue = 24D;
            _dayLength.MinValue = 0D;
            _dayLength.DefaultValue = 12D;
            _dayLength.Units = "hour";
            _dayLength.URL = "http://";
            _dayLength.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
            //   
            _meanAnnualAirTemp.Name = "meanAnnualAirTemp";
            _meanAnnualAirTemp.Description = "Annual Mean Air Temperature";
            _meanAnnualAirTemp.MaxValue = 80D;
            _meanAnnualAirTemp.MinValue = -30D;
            _meanAnnualAirTemp.DefaultValue = 22D;
            _meanAnnualAirTemp.Units = "°C";
            _meanAnnualAirTemp.URL = "http://";
            _meanAnnualAirTemp.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
        }
        #endregion
    }
}
