//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

/// 
/// This class was created from file C:\Users\mancealo\Documents\Sirius Quality\branches\TestSoil\Code\SiriusQuality-SoilTemperatureDomainClasses\XML\UNIMI.SoilT.Interfaces_States.xml
/// The tool used was: DCC - Domain Class Coder, http://components.biomamodelling.org/, DCC
/// 
/// Loic Manceau
/// loic.manceau@inra.fr
/// INRA
/// 
/// 
/// 5/8/2017 12:24:48 PM
/// 
namespace INRA.SiriusQualitySoilT.Interfaces
{
    using System;
    using CRA.ModelLayer.Core;
    
    
    /// <summary>StatesVarInfoClasses contain the attributes for each variable in the domain class RainData. Attributes are valorized via the static constructor. The data-type VarInfo causes  a dependency to the assembly CRA.Core.Preconditions.dll</summary>
    public class StatesVarInfo : IVarInfoClass
    {
        
        #region Private fields
        static VarInfo _maxTSoil = new VarInfo();
        
        static VarInfo _minTSoil = new VarInfo();
        
        static VarInfo _hourlySoilT = new VarInfo();
        #endregion
        
        /// <summary>Constructor</summary>
        static StatesVarInfo()
        {
            StatesVarInfo.DescribeVariables();
        }
        
        #region IVarInfoClass members
        /// <summary>Domain Class description</summary>
        public virtual  string Description
        {
            get
            {
                return "State variables of SoilT";
            }
        }
        
        /// <summary>Reference to the ontology</summary>
        public  string URL
        {
            get
            {
                return "http://";
            }
        }
        
        /// <summary>Value domain class of reference</summary>
        public  string DomainClassOfReference
        {
            get
            {
                return "States";
            }
        }
        #endregion
        
        #region Public properties
        /// <summary>Maximum Soil Temperature</summary>
        public static  VarInfo maxTSoil
        {
            get
            {
                return  _maxTSoil;
            }
        }
        
        /// <summary>Minimum Soil Temperature</summary>
        public static  VarInfo minTSoil
        {
            get
            {
                return  _minTSoil;
            }
        }
        
        /// <summary>Hourly Soil Temperature</summary>
        public static  VarInfo hourlySoilT
        {
            get
            {
                return  _hourlySoilT;
            }
        }
        #endregion
        
        #region VarInfo values
        /// <summary>Set VarInfo values</summary>
        static void DescribeVariables()
        {
            //   
            _maxTSoil.Name = "maxTSoil";
            _maxTSoil.Description = "Maximum Soil Temperature";
            _maxTSoil.MaxValue = 80D;
            _maxTSoil.MinValue = -30D;
            _maxTSoil.DefaultValue = 20D;
            _maxTSoil.Units = "°C";
            _maxTSoil.URL = "http://";
            _maxTSoil.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
            //   
            _minTSoil.Name = "minTSoil";
            _minTSoil.Description = "Minimum Soil Temperature";
            _minTSoil.MaxValue = 80D;
            _minTSoil.MinValue = -30D;
            _minTSoil.DefaultValue = 20D;
            _minTSoil.Units = "°C";
            _minTSoil.URL = "http://";
            _minTSoil.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
            //   
            _hourlySoilT.Name = "hourlySoilT";
            _hourlySoilT.Description = "Hourly Soil Temperature";
            _hourlySoilT.MaxValue = 80D;
            _hourlySoilT.MinValue = -30D;
            _hourlySoilT.DefaultValue = 20D;
            _hourlySoilT.Units = "°C";
            _hourlySoilT.URL = "http://";
            _hourlySoilT.ValueType = VarInfoValueTypes.GetInstanceForName("ArrayDouble");
        }
        #endregion
    }
}
