
# -*- coding: latin-1 -*-
# This file has been generated at Tue Jun 17 17:18:39 2025

from openalea.core import *


__name__ = 'amei.apsim_.soiltemp'

__editable__ = True
__version__ = '0.0.1'
__license__ = 'CECILL-C'
__authors__ = 'AMEI Consortium'
__institutes__ = ''
__description__ = 'CropML Model library.'
__url__ = 'http://crop2ml.org'
__icon__ = ''
__alias__ = ['Soiltemp']


__all__ = ['soiltemperature_model_soiltemperature', 'Soiltemp']



soiltemperature_model_soiltemperature = Factory(name='SoilTemperature',
                authors='AMEI Consortium (wralea authors)',
                description=' Soil Temperature ',
                category='Unclassified',
                nodemodule='soiltemperature',
                nodeclass='model_soiltemperature',
                inputs=[{'name': 'weather_MinT', 'interface': IFloat, 'value': 0}, {'name': 'weather_MaxT', 'interface': IFloat, 'value': 0}, {'name': 'weather_MeanT', 'interface': IFloat, 'value': 0}, {'name': 'weather_Tav', 'interface': IFloat, 'value': 0}, {'name': 'weather_Amp', 'interface': IFloat, 'value': 0}, {'name': 'weather_AirPressure', 'interface': IFloat, 'value': 0}, {'name': 'weather_Wind', 'interface': IFloat, 'value': 0}, {'name': 'weather_Latitude', 'interface': IFloat, 'value': 0}, {'name': 'weather_Radn', 'interface': IFloat, 'value': 0}, {'name': 'clock_Today_DayOfYear', 'interface': IInt, 'value': 0}, {'name': 'microClimate_CanopyHeight', 'interface': IFloat, 'value': 0}, {'name': 'physical_Thickness', 'interface': ISequence, 'value': 0}, {'name': 'physical_BD', 'interface': ISequence, 'value': 0}, {'name': 'ps', 'interface': IFloat, 'value': 0}, {'name': 'physical_Rocks', 'interface': ISequence, 'value': 0}, {'name': 'physical_ParticleSizeSand', 'interface': ISequence, 'value': 0}, {'name': 'physical_ParticleSizeSilt', 'interface': ISequence, 'value': 0}, {'name': 'physical_ParticleSizeClay', 'interface': ISequence, 'value': 0}, {'name': 'organic_Carbon', 'interface': ISequence, 'value': 0}, {'name': 'waterBalance_SW', 'interface': ISequence, 'value': 0}, {'name': 'waterBalance_Eos', 'interface': IFloat, 'value': 0}, {'name': 'waterBalance_Eo', 'interface': IFloat, 'value': 0}, {'name': 'waterBalance_Es', 'interface': IFloat, 'value': 0}, {'name': 'waterBalance_Salb', 'interface': IFloat, 'value': 0}, {'name': 'InitialValues', 'interface': ISequence, 'value': 0}, {'name': 'pInitialValues', 'interface': ISequence, 'value': 0}, {'name': 'DepthToConstantTemperature', 'interface': IFloat, 'value': 10000}, {'name': 'timestep', 'interface': IFloat, 'value': 86400.0}, {'name': 'latentHeatOfVapourisation', 'interface': IFloat, 'value': 2465000}, {'name': 'stefanBoltzmannConstant', 'interface': IFloat, 'value': 5.67e-08}, {'name': 'airNode', 'interface': IInt, 'value': 0}, {'name': 'surfaceNode', 'interface': IInt, 'value': 1}, {'name': 'topsoilNode', 'interface': IInt, 'value': 2}, {'name': 'numPhantomNodes', 'interface': IInt, 'value': 5}, {'name': 'constantBoundaryLayerConductance', 'interface': IFloat, 'value': 20}, {'name': 'numIterationsForBoundaryLayerConductance', 'interface': IInt, 'value': 1}, {'name': 'defaultTimeOfMaximumTemperature', 'interface': IFloat, 'value': 14.0}, {'name': 'defaultInstrumentHeight', 'interface': IFloat, 'value': 1.2}, {'name': 'bareSoilRoughness', 'interface': IFloat, 'value': 57}, {'name': 'doInitialisationStuff', 'interface': IBool, 'value': 'False'}, {'name': 'internalTimeStep', 'interface': IFloat, 'value': 0}, {'name': 'timeOfDaySecs', 'interface': IFloat, 'value': 0}, {'name': 'numNodes', 'interface': IInt, 'value': 0}, {'name': 'numLayers', 'interface': IInt, 'value': 0}, {'name': 'nodeDepth', 'interface': ISequence, 'value': 0}, {'name': 'thermCondPar1', 'interface': ISequence, 'value': 0}, {'name': 'thermCondPar2', 'interface': ISequence, 'value': 0}, {'name': 'thermCondPar3', 'interface': ISequence, 'value': 0}, {'name': 'thermCondPar4', 'interface': ISequence, 'value': 0}, {'name': 'volSpecHeatSoil', 'interface': ISequence, 'value': 0}, {'name': 'soilTemp', 'interface': ISequence, 'value': 0}, {'name': 'morningSoilTemp', 'interface': ISequence, 'value': 0}, {'name': 'heatStorage', 'interface': ISequence, 'value': 0}, {'name': 'thermalConductance', 'interface': ISequence, 'value': 0}, {'name': 'thermalConductivity', 'interface': ISequence, 'value': 0}, {'name': 'boundaryLayerConductance', 'interface': IFloat, 'value': 0}, {'name': 'newTemperature', 'interface': ISequence, 'value': 0}, {'name': 'airTemperature', 'interface': IFloat, 'value': 0}, {'name': 'maxTempYesterday', 'interface': IFloat, 'value': 0}, {'name': 'minTempYesterday', 'interface': IFloat, 'value': 0}, {'name': 'soilWater', 'interface': ISequence, 'value': 0}, {'name': 'minSoilTemp', 'interface': ISequence, 'value': 0}, {'name': 'maxSoilTemp', 'interface': ISequence, 'value': 0}, {'name': 'aveSoilTemp', 'interface': ISequence, 'value': 0}, {'name': 'aveSoilWater', 'interface': ISequence, 'value': 0}, {'name': 'thickness', 'interface': ISequence, 'value': 0}, {'name': 'bulkDensity', 'interface': ISequence, 'value': 0}, {'name': 'rocks', 'interface': ISequence, 'value': 0}, {'name': 'carbon', 'interface': ISequence, 'value': 0}, {'name': 'sand', 'interface': ISequence, 'value': 0}, {'name': 'pom', 'interface': IFloat, 'value': 0}, {'name': 'silt', 'interface': ISequence, 'value': 0}, {'name': 'clay', 'interface': ISequence, 'value': 0}, {'name': 'soilRoughnessHeight', 'interface': IFloat, 'value': 0}, {'name': 'instrumentHeight', 'interface': IFloat, 'value': 0}, {'name': 'netRadiation', 'interface': IFloat, 'value': 0}, {'name': 'canopyHeight', 'interface': IFloat, 'value': 0}, {'name': 'instrumHeight', 'interface': IFloat, 'value': 0}, {'name': 'nu', 'interface': IFloat, 'value': 0.6}, {'name': 'boundarLayerConductanceSource', 'interface': IStr, 'value': 'calc'}, {'name': 'netRadiationSource', 'interface': IStr, 'value': 'calc'}, {'name': 'MissingValue', 'interface': IFloat, 'value': 99999}, {'name': 'soilConstituentNames', 'interface': None, 'value': ['Rocks', 'OrganicMatter', 'Sand', 'Silt', 'Clay', 'Water', 'Ice', 'Air']}],
                outputs=[{'name': 'heatStorage', 'interface': ISequence}, {'name': 'instrumentHeight', 'interface': IFloat}, {'name': 'canopyHeight', 'interface': IFloat}, {'name': 'minSoilTemp', 'interface': ISequence}, {'name': 'maxSoilTemp', 'interface': ISequence}, {'name': 'aveSoilTemp', 'interface': ISequence}, {'name': 'volSpecHeatSoil', 'interface': ISequence}, {'name': 'soilTemp', 'interface': ISequence}, {'name': 'morningSoilTemp', 'interface': ISequence}, {'name': 'newTemperature', 'interface': ISequence}, {'name': 'thermalConductivity', 'interface': ISequence}, {'name': 'thermalConductance', 'interface': ISequence}, {'name': 'boundaryLayerConductance', 'interface': IFloat}, {'name': 'soilWater', 'interface': ISequence}, {'name': 'doInitialisationStuff', 'interface': IBool}, {'name': 'maxTempYesterday', 'interface': IFloat}, {'name': 'minTempYesterday', 'interface': IFloat}, {'name': 'airTemperature', 'interface': IFloat}, {'name': 'internalTimeStep', 'interface': IFloat}, {'name': 'timeOfDaySecs', 'interface': IFloat}, {'name': 'netRadiation', 'interface': IFloat}, {'name': 'InitialValues', 'interface': ISequence}],
                widgetmodule=None,
                widgetclass=None,
               )




Soiltemp = CompositeNodeFactory(name='Soiltemp',
                             description=('\n'
 '\n'
 '    Soiltemp model\n'
 '    -Version: 2.0  -Time step: 1.0\n'
 '    Authors: Cyrille\n'
 '    Reference: None\n'
 '    Institution: INRAE\n'
 '    ExtendedDescription: Soil Temperature\n'
 '    ShortDescription: Soil Temperature\n'),
                             category='',
                             doc='',
                             inputs=[  {'interface': IFloat, 'name': 'netRadiation'},
   {'interface': ISequence, 'name': 'aveSoilWater'},
   {'interface': ISequence, 'name': 'bulkDensity'},
   {'interface': IFloat, 'name': 'waterBalance_Eo'},
   {'interface': ISequence, 'name': 'thermCondPar1'},
   {'interface': IInt, 'name': 'topsoilNode', 'value': 2},
   {'interface': IInt, 'name': 'surfaceNode', 'value': 1},
   {'interface': IFloat, 'name': 'internalTimeStep'},
   {'interface': ISequence, 'name': 'thermalConductance'},
   {'interface': ISequence, 'name': 'thickness'},
   {'interface': IInt, 'name': 'numPhantomNodes', 'value': 5},
   {  'interface': None,
      'name': 'soilConstituentNames',
      'value': [  'Rocks',
                  'OrganicMatter',
                  'Sand',
                  'Silt',
                  'Clay',
                  'Water',
                  'Ice',
                  'Air']},
   {'interface': IBool, 'name': 'doInitialisationStuff', 'value': 'False'},
   {'interface': IFloat, 'name': 'maxTempYesterday'},
   {'interface': IFloat, 'name': 'waterBalance_Salb'},
   {'interface': ISequence, 'name': 'physical_Thickness'},
   {'interface': IFloat, 'name': 'MissingValue', 'value': 99999},
   {'interface': IFloat, 'name': 'timeOfDaySecs'},
   {'interface': IInt, 'name': 'numNodes'},
   {'interface': IFloat, 'name': 'timestep', 'value': 86400.0},
   {'interface': ISequence, 'name': 'organic_Carbon'},
   {'interface': IFloat, 'name': 'waterBalance_Es'},
   {'interface': IFloat, 'name': 'weather_Wind'},
   {'interface': ISequence, 'name': 'soilWater'},
   {'interface': IFloat, 'name': 'soilRoughnessHeight'},
   {'interface': ISequence, 'name': 'physical_ParticleSizeSand'},
   {  'interface': IInt,
      'name': 'numIterationsForBoundaryLayerConductance',
      'value': 1},
   {'interface': ISequence, 'name': 'clay'},
   {'interface': IFloat, 'name': 'weather_AirPressure'},
   {'interface': ISequence, 'name': 'soilTemp'},
   {'interface': IInt, 'name': 'clock_Today_DayOfYear'},
   {'interface': ISequence, 'name': 'silt'},
   {  'interface': IFloat,
      'name': 'defaultTimeOfMaximumTemperature',
      'value': 14.0},
   {'interface': IFloat, 'name': 'pom'},
   {'interface': IFloat, 'name': 'DepthToConstantTemperature', 'value': 10000},
   {'interface': IFloat, 'name': 'microClimate_CanopyHeight'},
   {  'interface': IFloat,
      'name': 'constantBoundaryLayerConductance',
      'value': 20},
   {'interface': IFloat, 'name': 'waterBalance_Eos'},
   {'interface': IFloat, 'name': 'instrumentHeight'},
   {'interface': ISequence, 'name': 'thermCondPar4'},
   {'interface': ISequence, 'name': 'waterBalance_SW'},
   {'interface': IFloat, 'name': 'weather_Amp'},
   {'interface': ISequence, 'name': 'nodeDepth'},
   {'interface': IFloat, 'name': 'nu', 'value': 0.6},
   {'interface': ISequence, 'name': 'sand'},
   {'interface': ISequence, 'name': 'pInitialValues'},
   {'interface': IFloat, 'name': 'weather_MinT'},
   {'interface': IFloat, 'name': 'ps'},
   {'interface': IStr, 'name': 'netRadiationSource', 'value': 'calc'},
   {'interface': IFloat, 'name': 'weather_Radn'},
   {'interface': IInt, 'name': 'airNode'},
   {'interface': IInt, 'name': 'numLayers'},
   {'interface': ISequence, 'name': 'volSpecHeatSoil'},
   {'interface': IFloat, 'name': 'instrumHeight'},
   {'interface': IFloat, 'name': 'canopyHeight'},
   {'interface': ISequence, 'name': 'heatStorage'},
   {'interface': ISequence, 'name': 'minSoilTemp'},
   {'interface': IFloat, 'name': 'bareSoilRoughness', 'value': 57},
   {'interface': ISequence, 'name': 'thermCondPar2'},
   {'interface': IFloat, 'name': 'defaultInstrumentHeight', 'value': 1.2},
   {'interface': ISequence, 'name': 'maxSoilTemp'},
   {'interface': ISequence, 'name': 'physical_BD'},
   {'interface': IFloat, 'name': 'latentHeatOfVapourisation', 'value': 2465000},
   {'interface': IFloat, 'name': 'weather_Latitude'},
   {'interface': ISequence, 'name': 'physical_Rocks'},
   {'interface': IFloat, 'name': 'stefanBoltzmannConstant', 'value': 5.67e-08},
   {'interface': IFloat, 'name': 'weather_Tav'},
   {'interface': ISequence, 'name': 'newTemperature'},
   {'interface': IFloat, 'name': 'airTemperature'},
   {'interface': IFloat, 'name': 'weather_MaxT'},
   {  'interface': IStr,
      'name': 'boundarLayerConductanceSource',
      'value': 'calc'},
   {'interface': ISequence, 'name': 'thermalConductivity'},
   {'interface': IFloat, 'name': 'minTempYesterday'},
   {'interface': ISequence, 'name': 'carbon'},
   {'interface': IFloat, 'name': 'weather_MeanT'},
   {'interface': ISequence, 'name': 'rocks'},
   {'interface': ISequence, 'name': 'InitialValues'},
   {'interface': ISequence, 'name': 'thermCondPar3'},
   {'interface': ISequence, 'name': 'physical_ParticleSizeSilt'},
   {'interface': IFloat, 'name': 'boundaryLayerConductance'},
   {'interface': ISequence, 'name': 'physical_ParticleSizeClay'},
   {'interface': ISequence, 'name': 'aveSoilTemp'},
   {'interface': ISequence, 'name': 'morningSoilTemp'}],
                             outputs=[  {'interface': ISequence, 'name': 'heatStorage'},
   {'interface': IFloat, 'name': 'instrumentHeight'},
   {'interface': IFloat, 'name': 'canopyHeight'},
   {'interface': ISequence, 'name': 'minSoilTemp'},
   {'interface': ISequence, 'name': 'maxSoilTemp'},
   {'interface': ISequence, 'name': 'aveSoilTemp'},
   {'interface': ISequence, 'name': 'volSpecHeatSoil'},
   {'interface': ISequence, 'name': 'soilTemp'},
   {'interface': ISequence, 'name': 'morningSoilTemp'},
   {'interface': ISequence, 'name': 'newTemperature'},
   {'interface': ISequence, 'name': 'thermalConductivity'},
   {'interface': ISequence, 'name': 'thermalConductance'},
   {'interface': IFloat, 'name': 'boundaryLayerConductance'},
   {'interface': ISequence, 'name': 'soilWater'},
   {'interface': IBool, 'name': 'doInitialisationStuff'},
   {'interface': IFloat, 'name': 'maxTempYesterday'},
   {'interface': IFloat, 'name': 'minTempYesterday'},
   {'interface': IFloat, 'name': 'airTemperature'},
   {'interface': IFloat, 'name': 'internalTimeStep'},
   {'interface': IFloat, 'name': 'timeOfDaySecs'},
   {'interface': IFloat, 'name': 'netRadiation'},
   {'interface': ISequence, 'name': 'InitialValues'}],
                             elt_factory={2: ('amei.apsim_.soiltemp', 'SoilTemperature')},
                             elt_connections={  4309547152: (2, 0, '__out__', 0),
   4309547184: (2, 1, '__out__', 1),
   4309547216: (2, 2, '__out__', 2),
   4309547248: (2, 3, '__out__', 3),
   4309547280: (2, 4, '__out__', 4),
   4309547312: (2, 5, '__out__', 5),
   4309547344: (2, 6, '__out__', 6),
   4309547376: (2, 7, '__out__', 7),
   4309547408: (2, 8, '__out__', 8),
   4309547440: (2, 9, '__out__', 9),
   4309547472: (2, 10, '__out__', 10),
   4309547504: (2, 11, '__out__', 11),
   4309547536: (2, 12, '__out__', 12),
   4309547568: (2, 13, '__out__', 13),
   4309547600: (2, 14, '__out__', 14),
   4309547632: (2, 15, '__out__', 15),
   4309547664: (2, 16, '__out__', 16),
   4309547696: (2, 17, '__out__', 17),
   4309547728: (2, 18, '__out__', 18),
   4309547760: (2, 19, '__out__', 19),
   4309547792: (2, 20, '__out__', 20),
   4309547824: (2, 21, '__out__', 21),
   4309547856: ('__in__', 0, 2, 75),
   4309547888: ('__in__', 1, 2, 64),
   4309547920: ('__in__', 2, 2, 66),
   4309547952: ('__in__', 3, 2, 21),
   4309547984: ('__in__', 4, 2, 45),
   4309548016: ('__in__', 5, 2, 32),
   4309548048: ('__in__', 6, 2, 31),
   4309548080: ('__in__', 7, 2, 40),
   4309548112: ('__in__', 8, 2, 53),
   4309548144: ('__in__', 9, 2, 65),
   4309548176: ('__in__', 10, 2, 33),
   4309548208: ('__in__', 11, 2, 82),
   4309548240: ('__in__', 12, 2, 39),
   4309548272: ('__in__', 13, 2, 58),
   4309548304: ('__in__', 14, 2, 23),
   4309548336: ('__in__', 15, 2, 11),
   4309548368: ('__in__', 16, 2, 81),
   4309548400: ('__in__', 17, 2, 41),
   4309548432: ('__in__', 18, 2, 42),
   4309548464: ('__in__', 19, 2, 27),
   4309548496: ('__in__', 20, 2, 18),
   4309548528: ('__in__', 21, 2, 22),
   4309548560: ('__in__', 22, 2, 6),
   4309548592: ('__in__', 23, 2, 60),
   4309548624: ('__in__', 24, 2, 73),
   4309548656: ('__in__', 25, 2, 15),
   4309548688: ('__in__', 26, 2, 35),
   4309548720: ('__in__', 27, 2, 72),
   4309548752: ('__in__', 28, 2, 5),
   4309548784: ('__in__', 29, 2, 50),
   4309548816: ('__in__', 30, 2, 9),
   4309548848: ('__in__', 31, 2, 71),
   4309548880: ('__in__', 32, 2, 36),
   4309548912: ('__in__', 33, 2, 70),
   4309548944: ('__in__', 34, 2, 26),
   4309548976: ('__in__', 35, 2, 10),
   4309549008: ('__in__', 36, 2, 34),
   4309549040: ('__in__', 37, 2, 20),
   4309549072: ('__in__', 38, 2, 74),
   4309549104: ('__in__', 39, 2, 48),
   4309549136: ('__in__', 40, 2, 19),
   4309549168: ('__in__', 41, 2, 4),
   4309549200: ('__in__', 42, 2, 44),
   4309549232: ('__in__', 43, 2, 78),
   4309549264: ('__in__', 44, 2, 69),
   4309549296: ('__in__', 45, 2, 25),
   4309549328: ('__in__', 46, 2, 0),
   4309549360: ('__in__', 47, 2, 13),
   4309549392: ('__in__', 48, 2, 80),
   4309549424: ('__in__', 49, 2, 8),
   4309549456: ('__in__', 50, 2, 30),
   4309549488: ('__in__', 51, 2, 43),
   4309549520: ('__in__', 52, 2, 49),
   4309549552: ('__in__', 53, 2, 77),
   4309549584: ('__in__', 54, 2, 76),
   4309549616: ('__in__', 55, 2, 52),
   4309549648: ('__in__', 56, 2, 61),
   4309549680: ('__in__', 57, 2, 38),
   4309549712: ('__in__', 58, 2, 46),
   4309549744: ('__in__', 59, 2, 37),
   4309549776: ('__in__', 60, 2, 62),
   4309549808: ('__in__', 61, 2, 12),
   4309549840: ('__in__', 62, 2, 28),
   4309549872: ('__in__', 63, 2, 7),
   4309549904: ('__in__', 64, 2, 14),
   4309549936: ('__in__', 65, 2, 29),
   4309549968: ('__in__', 66, 2, 3),
   4309550000: ('__in__', 67, 2, 56),
   4309550032: ('__in__', 68, 2, 57),
   4309550064: ('__in__', 69, 2, 1),
   4309550096: ('__in__', 70, 2, 79),
   4309550128: ('__in__', 71, 2, 54),
   4309550160: ('__in__', 72, 2, 59),
   4309550192: ('__in__', 73, 2, 68),
   4309550224: ('__in__', 74, 2, 2),
   4309550256: ('__in__', 75, 2, 67),
   4309550288: ('__in__', 76, 2, 24),
   4309550320: ('__in__', 77, 2, 47),
   4309550352: ('__in__', 78, 2, 16),
   4309550384: ('__in__', 79, 2, 55),
   4309550416: ('__in__', 80, 2, 17),
   4309550448: ('__in__', 81, 2, 63),
   4309550480: ('__in__', 82, 2, 51)},
                             elt_data={  2: {  'block': False,
         'caption': 'SoilTemperature',
         'delay': 0,
         'hide': True,
         'id': 2,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 0,
         'posy': 250.0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 250.0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 250.0,
                 'posy': 500,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={2: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  2: {'position': [0, 250.0], 'userColor': None, 'useUserColor': True},
   '__in__': {'position': [250.0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [250.0, 500], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             eval_algo=None,
                             )




