[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"
[project]
name = "DSSAT_EPICST_standalone"
authors = [{name = "Kenneth N. Potter , Jimmy R. Williams "}]
description=""
version="0.1"
dependencies = ["pandas","numpy"]