[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"
[project]
name = "Simplace_Soil_Temperature"
authors = [{name = "Gunther Krauss"}]
description=""
version="0.1"
dependencies = ["pandas","numpy"]