//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

/// 
/// This class was created from file C:\Users\mancealo\Documents\Sirius Quality\branches\TestSoil\Code\SiriusQuality-SoilTemperatureDomainClasses\XML\UNIMI.SoilT.Interfaces_RatesExternal.xml
/// The tool used was: DCC - Domain Class Coder, http://components.biomamodelling.org/, DCC
/// 
/// Loic Manceau
/// loic.manceau@inra.fr
/// INRA
/// 
/// 
/// 5/8/2017 12:23:20 PM
/// 
namespace INRA.SiriusQualitySoilT.Interfaces
{
    using System;
    using CRA.ModelLayer.Core;
    
    
    /// <summary>RatesExternalVarInfoClasses contain the attributes for each variable in the domain class RainData. Attributes are valorized via the static constructor. The data-type VarInfo causes  a dependency to the assembly CRA.Core.Preconditions.dll</summary>
    public class RatesExternalVarInfo : IVarInfoClass
    {
        
        #region Private fields
        static VarInfo _heatFlux = new VarInfo();
        #endregion
        
        /// <summary>Constructor</summary>
        static RatesExternalVarInfo()
        {
            RatesExternalVarInfo.DescribeVariables();
        }
        
        #region IVarInfoClass members
        /// <summary>Domain Class description</summary>
        public virtual  string Description
        {
            get
            {
                return "Rates external of the SoilT component";
            }
        }
        
        /// <summary>Reference to the ontology</summary>
        public  string URL
        {
            get
            {
                return "http://";
            }
        }
        
        /// <summary>Value domain class of reference</summary>
        public  string DomainClassOfReference
        {
            get
            {
                return "RatesExternal";
            }
        }
        #endregion
        
        #region Public properties
        /// <summary>Soil Heat Flux from Energy Balance Component</summary>
        public static  VarInfo heatFlux
        {
            get
            {
                return  _heatFlux;
            }
        }
        #endregion
        
        #region VarInfo values
        /// <summary>Set VarInfo values</summary>
        static void DescribeVariables()
        {
            //   
            _heatFlux.Name = "heatFlux";
            _heatFlux.Description = "Soil Heat Flux from Energy Balance Component";
            _heatFlux.MaxValue = 100D;
            _heatFlux.MinValue = 0D;
            _heatFlux.DefaultValue = 50D;
            _heatFlux.Units = "g m-2 d-1";
            _heatFlux.URL = "http://";
            _heatFlux.ValueType = VarInfoValueTypes.GetInstanceForName("Double");
        }
        #endregion
    }
}
