[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"
[project]
name = "SQ_Soil_Temperature"
authors = [{name = "loic.manceau@inra.fr"}]
description=""
version="0.1"
dependencies = ["pandas","numpy"]