[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"
[project]
name = "Monica_SoilTemp"
authors = [{name = "Michael Berg-Mohnicke"}]
description=""
version="0.1"
dependencies = ["pandas","numpy"]