from datetime import datetime
from math import *
from Campbell.campbell import model_campbell
def model_model_soiltempcampbell(int NLAYR,
      float THICK[NLAYR],
      float BD[NLAYR],
      float SLCARB[NLAYR],
      float CLAY[NLAYR],
      float SLROCK[NLAYR],
      float SLSILT[NLAYR],
      float SLSAND[NLAYR],
      float SW[NLAYR],
      floatlist THICKApsim,
      floatlist DEPTHApsim,
      float CONSTANT_TEMPdepth,
      floatlist BDApsim,
      float T2M,
      float TMAX,
      float TMIN,
      float TAV,
      float TAMP,
      float XLAT,
      floatlist CLAYApsim,
      floatlist SWApsim,
      int DOY,
      float airPressure,
      float canopyHeight,
      float SALB,
      float SRAD,
      float ESP,
      float ES,
      float EOAD,
      floatlist soilTemp,
      floatlist newTemperature,
      floatlist minSoilTemp,
      floatlist maxSoilTemp,
      floatlist aveSoilTemp,
      floatlist morningSoilTemp,
      floatlist thermalCondPar1,
      floatlist thermalCondPar2,
      floatlist thermalCondPar3,
      floatlist thermalCondPar4,
      floatlist thermalConductivity,
      floatlist thermalConductance,
      floatlist heatStorage,
      floatlist volSpecHeatSoil,
      float maxTempYesterday,
      float minTempYesterday,
      float instrumentHeight,
      str boundaryLayerConductanceSource,
      str netRadiationSource,
      float windSpeed,
      floatlist SLCARBApsim,
      floatlist SLROCKApsim,
      floatlist SLSILTApsim,
      floatlist SLSANDApsim,
      float _boundaryLayerConductance):
    soilTemp, minSoilTemp, maxSoilTemp, aveSoilTemp, morningSoilTemp, newTemperature, maxTempYesterday, minTempYesterday, thermalCondPar1, thermalCondPar2, thermalCondPar3, thermalCondPar4, thermalConductivity, thermalConductance, heatStorage, volSpecHeatSoil, _boundaryLayerConductance, THICKApsim, DEPTHApsim, BDApsim, SWApsim, CLAYApsim, SLROCKApsim, SLCARBApsim, SLSANDApsim, SLSILTApsim = model_campbell(NLAYR,THICK,BD,SLCARB,CLAY,SLROCK,SLSILT,SLSAND,SW,THICKApsim,DEPTHApsim,CONSTANT_TEMPdepth,BDApsim,T2M,TMAX,TMIN,TAV,TAMP,XLAT,CLAYApsim,SWApsim,DOY,airPressure,canopyHeight,SALB,SRAD,ESP,ES,EOAD,soilTemp,newTemperature,minSoilTemp,maxSoilTemp,aveSoilTemp,morningSoilTemp,thermalCondPar1,thermalCondPar2,thermalCondPar3,thermalCondPar4,thermalConductivity,thermalConductance,heatStorage,volSpecHeatSoil,maxTempYesterday,minTempYesterday,instrumentHeight,boundaryLayerConductanceSource,netRadiationSource,windSpeed,SLCARBApsim,SLROCKApsim,SLSILTApsim,SLSANDApsim,_boundaryLayerConductance)

    return soilTemp, minSoilTemp, maxSoilTemp, aveSoilTemp, morningSoilTemp, newTemperature, maxTempYesterday, minTempYesterday, thermalCondPar1, thermalCondPar2, thermalCondPar3, thermalCondPar4, thermalConductivity, thermalConductance, heatStorage, volSpecHeatSoil, _boundaryLayerConductance, THICKApsim, DEPTHApsim, BDApsim, SWApsim, CLAYApsim, SLROCKApsim, SLCARBApsim, SLSANDApsim, SLSILTApsim