from datetime import datetime
from math import *
from Campbell.campbell import model_campbell
def model_model_soiltempcampbell(int NLAYR,
      float THICK[NLAYR],
      float BD[NLAYR],
      float SLCARB[NLAYR],
      float CLAY[NLAYR],
      float SLROCK[NLAYR],
      float SLSILT[NLAYR],
      float SLSAND[NLAYR],
      float SW[NLAYR],
      float THICKApsim[NLAYR],
      float DEPTHApsim[NLAYR],
      float CONSTANT_TEMPdepth,
      float BDApsim[NLAYR],
      float T2M,
      float TMAX,
      float TMIN,
      float TAV,
      float TAMP,
      float XLAT,
      float CLAYApsim[NLAYR],
      float SWApsim[NLAYR],
      int DOY,
      float airPressure,
      float canopyHeight,
      float SALB,
      float SRAD,
      float ESP,
      float ES,
      float EOAD,
      float soilTemp[NLAYR],
      float newTemperature[NLAYR],
      float minSoilTemp[NLAYR],
      float maxSoilTemp[NLAYR],
      float aveSoilTemp[NLAYR],
      float morningSoilTemp[NLAYR],
      float thermalCondPar1[NLAYR],
      float thermalCondPar2[NLAYR],
      float thermalCondPar3[NLAYR],
      float thermalCondPar4[NLAYR],
      float thermalConductivity[NLAYR],
      float thermalConductance[NLAYR],
      float heatStorage[NLAYR],
      float volSpecHeatSoil[NLAYR],
      float maxTempYesterday,
      float minTempYesterday,
      float instrumentHeight,
      str boundaryLayerConductanceSource,
      str netRadiationSource,
      float windSpeed,
      float SLCARBApsim[NLAYR],
      float SLROCKApsim[NLAYR],
      float SLSILTApsim[NLAYR],
      float SLSANDApsim[NLAYR],
      float _boundaryLayerConductance):
    soilTemp, minSoilTemp, maxSoilTemp, aveSoilTemp, morningSoilTemp, newTemperature, maxTempYesterday, minTempYesterday, thermalCondPar1, thermalCondPar2, thermalCondPar3, thermalCondPar4, thermalConductivity, thermalConductance, heatStorage, volSpecHeatSoil, _boundaryLayerConductance, THICKApsim, DEPTHApsim, BDApsim, SWApsim, CLAYApsim, SLROCKApsim, SLCARBApsim, SLSANDApsim, SLSILTApsim = model_campbell(NLAYR,THICK,BD,SLCARB,CLAY,SLROCK,SLSILT,SLSAND,SW,THICKApsim,DEPTHApsim,CONSTANT_TEMPdepth,BDApsim,T2M,TMAX,TMIN,TAV,TAMP,XLAT,CLAYApsim,SWApsim,DOY,airPressure,canopyHeight,SALB,SRAD,ESP,ES,EOAD,soilTemp,newTemperature,minSoilTemp,maxSoilTemp,aveSoilTemp,morningSoilTemp,thermalCondPar1,thermalCondPar2,thermalCondPar3,thermalCondPar4,thermalConductivity,thermalConductance,heatStorage,volSpecHeatSoil,maxTempYesterday,minTempYesterday,instrumentHeight,boundaryLayerConductanceSource,netRadiationSource,windSpeed,SLCARBApsim,SLROCKApsim,SLSILTApsim,SLSANDApsim,_boundaryLayerConductance)

    return soilTemp, minSoilTemp, maxSoilTemp, aveSoilTemp, morningSoilTemp, newTemperature, maxTempYesterday, minTempYesterday, thermalCondPar1, thermalCondPar2, thermalCondPar3, thermalCondPar4, thermalConductivity, thermalConductance, heatStorage, volSpecHeatSoil, _boundaryLayerConductance, THICKApsim, DEPTHApsim, BDApsim, SWApsim, CLAYApsim, SLROCKApsim, SLCARBApsim, SLSANDApsim, SLSILTApsim